<form
    action="<?=APP::config('url') ?>program/promjena" 
    method="POST">

    <label>Naziv
        <input type="text" name="naziv" 
        value="<?=$program->naziv?>" />
    </label>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Opis
                <textarea name="opis" cols="30" 
                rows="5"><?=$program->opis?></textarea>
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Cijena
                <input type="number" name="cijena" 
                value="<?=$program->cijena?>"/>
            </label>
            <label>Verificiran
                <select name="verificiran">
                    <option <?php 
                    if($program->verificiran==='1'){
                        echo ' selected="selected" ';
                    }
                    ?> value="1">Da</option>
                    <option <?php 
                    if($program->verificiran==='0'){
                        echo ' selected="selected" ';
                    }
                    ?> value="0">Ne</option>
                </select>
            </label>
        </div>
    </div>

    <input type="hidden" name="sifra" value="<?=$program->sifra ?>" />

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>program/index">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Promjeni program"></input>
        </div>
    </div>

</form>