<form
    action="<?=APP::config('url') ?>ucenik/promjena" 
    method="POST">

    

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Ime
                <input type="text" name="ime" 
                value="<?=$entitet->ime?>" />
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Prezime
                <input type="text" name="prezime" 
                value="<?=$entitet->prezime?>" />
            </label>
        </div>

        <div class="large-6 small-12 cell">
            <label>Broj ugovora
                <input type="text" name="brojugovora" 
                value="<?=$entitet->brojugovora?>" />
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>OIB
                <input type="text" name="oib" 
                value="<?=$entitet->oib?>" />
            </label>
        </div>

        <div class="large-12 small-12 cell">
            <label>Email
                <input type="text" name="email" 
                value="<?=$entitet->email?>" />
            </label>
        </div>
    </div>

    <input type="hidden" name="sifra" value="<?=$entitet->sifra ?>" />


    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>ucenik/index?stranica=<?=$trenutna?>">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Promjeni ucenik"></input>
        </div>
    </div>

</form>