<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=APP::config('url') ?>view/styles.css">
    <title>Document</title>
</head>

<body>
    <h4>
        <strong>Vlasnik POUM: Marijan Mikić</strong>
        
    </h4>
<div class="container">
        Djelatnost je temeljena na konceptu cjeloživotnog učenja te u programima POUM-a sudjeluju polaznici od
        predškolske dobi do osoba treće dobi. Težište je na strukovnom obrazovanju i osposobljavanju odraslih osoba.
        POUM provodi programe osnovnoškolskog i srednjoškolskog obrazovanja odraslih te brojne programe strukovnog
        obrazovanja i osposobljavanja, Uz to organizira se niz programa kreativnih radionica, tečajeva i usavršavanja
        (likovnih, plesnih, glazbenih, dramskih). POUM uz stručno osposobljavanje,nudi brojne programe koji razvijaju
        kreativnost, interkulturalne kompetencije i jačanju socijalne i komunikacijske vještine. Naši programi su
        namijenjeni za tvrtke, starije osobe, studente ili određene ciljne skupine u okviru različitih projekata za
        koje smo posebno dizajnirali programe.
</div>
<div class="container2">
    <p>
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13706.540138107344!2d18.247037962663722!3d45.255934625325466!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475dac62a850c873%3A0xbb4e0a7bf0a2c366!2s31411%2C%20Trnava!5e1!3m2!1shr!2shr!4v1601727315720!5m2!1shr!2shr"
            width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
            tabindex="0">
        </iframe>
    </p>
    <p>
        <strong>Adresa:</strong>
        <br>Braće Radića 32
        <br>31411 Trnava
    </p>
    

</div>





</body>

</html>



