<!doctype html>
<html class="no-js" lang="en">
  <head>
    <?php include_once 'predlozak/head.phtml'; ?>
  </head>
  <body>
    <body style="background-color: dimgrey">
    <div class="grid-container">
      <?php include_once 'predlozak/izbornik.phtml'; ?>
      <div class="grid-x">
        <div class="large-12 small-12 cell">
          <div class="callout" style="min-height: 800px; background-image: url(public/img/knjige01.jpg); background-size: cover">
            <?php echo $sadrzaj; ?>
          </div>
        </div>
      </div>
      <?php include_once 'predlozak/podnozje.phtml'; ?>
    </div>
  <?php include_once 'predlozak/skripte.phtml'; ?>
  </body>
</html>
